#!/usr/bin/env bash
# Generate @krpc-starter/api-client from the Java *-api contracts (krpc's native generator
# ext-rpc-gen, class-based + krpc-base runtime). Output goes to OUT_DIR for a frontend workspace
# package, or for CI to publish.
#
# Usage:
#   scripts/gen-ts.sh [OUT_DIR]          # generate + assemble the package
#   scripts/gen-ts.sh generated-ts check # + npm install + tsc --noEmit (needs npm/network)
#
# In this monorepo the committed, consumed copy lives at ../frontend/packages/api-client; the root
# `api-client-freshness` CI job regenerates over it and fails on any drift (git diff --exit-code).
# The output is DETERMINISTIC — the normalization step below strips the generator's per-run
# timestamp headers and the class-validator validation decorators (a TS client needs neither: the
# field shape is the contract; validation is the server's job), so re-running yields byte-identical
# files and the frontend consumes the DTOs with zero decorator/runtime dependency.
set -euo pipefail

cd "$(dirname "$0")/.."   # repo root

OUT_DIR="${1:-generated-ts}"
DO_CHECK="${2:-}"
PKG_NAME="${PKG_NAME:-@krpc-starter/api-client}"
PKG_VERSION="${PKG_VERSION:-$(grep '^apiClientVersion=' gradle.properties | cut -d= -f2)}"
# npm registry to publish to / consume the @starter scope from. Override via env in CI.
# Placeholder registry.example.com — set NPM_REGISTRY to your own. URL must end with a slash.
NPM_REGISTRY="${NPM_REGISTRY:-https://registry.example.com/}"

echo ">> generating TS into ${OUT_DIR}/src (package ${PKG_NAME}@${PKG_VERSION})"
rm -rf "${OUT_DIR}"
mkdir -p "${OUT_DIR}/src"

# (1) real krpc generator: scans @UnsafeWeb @RpcService (com.example.*) → *-service.ts + DTOs.
GRADLE="${GRADLE:-./gradlew}"
"${GRADLE}" :ts-gen:genTs -PtsOutDir="${PWD}/${OUT_DIR}/src" --console=plain

# (1b) determinism + frontend-consumability normalization (see header). Per generated .ts file:
#   - strip the generator's per-run timestamp header (`foo.ts  2026-..T..+..`) → stable diff;
#   - drop the class-validator import block + the standalone @Decorator(...) lines, so the DTOs are
#     plain interfaces/classes any TS toolchain (SWC/esbuild/metro/tsc) bundles with no decorator
#     config and no class-validator runtime dep.
for f in "${OUT_DIR}"/src/*.ts; do
  perl -0777 -i -pe '
    s!(\S+\.ts)\s{2,}\d{4}-\d\d-\d\dT[0-9:+\-]+Z?!$1!g;
    s!import\s*\{[^}]*\}\s*from\s*\x27class-validator\x27;\s*\n!!g;
    s!^[ \t]*\@[A-Za-z]\w*(?:\([^)]*\))?[ \t]*\n!!mg;
  ' "$f"
done

# (2) index.ts: re-export every generated file.
{
  echo "// GENERATED by scripts/gen-ts.sh — re-exports the krpc-generated client"
  for f in "${OUT_DIR}"/src/*.ts; do
    base="$(basename "$f" .ts)"
    [ "$base" = "index" ] && continue
    echo "export * from './${base}';"
  done
} > "${OUT_DIR}/src/index.ts"

# (3) package.json: krpc-base carries the RpcService/R/MethodConfig types the *-service.ts imports
# (type-only → erased at runtime). Validation decorators are normalized out (1b), so no
# class-validator dependency.
cat > "${OUT_DIR}/package.json" <<JSON
{
  "name": "${PKG_NAME}",
  "version": "${PKG_VERSION}",
  "description": "Generated TypeScript client for the krpc-service-starter *-api contracts (single source of truth).",
  "license": "Apache-2.0",
  "type": "module",
  "main": "./src/index.ts",
  "types": "./src/index.ts",
  "files": ["src"],
  "dependencies": {
    "krpc-base": "^1.0.0"
  },
  "devDependencies": {
    "typescript": "^5.6.0"
  },
  "publishConfig": {
    "access": "restricted",
    "registry": "${NPM_REGISTRY}"
  }
}
JSON

# (4) tsconfig.json: plain interfaces/classes after normalization — no decorator options needed.
cat > "${OUT_DIR}/tsconfig.json" <<'JSON'
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "strictPropertyInitialization": false,
    "skipLibCheck": true,
    "noEmit": true
  },
  "include": ["src/**/*.ts"]
}
JSON

echo ">> assembled ${OUT_DIR}/ (frontend: npm i ${OUT_DIR}, or package.json \"${PKG_NAME}\": \"file:../${OUT_DIR}\")"

# (5) optional: tsc check (needs npm + network to pull krpc-base / class-validator / typescript).
if [ "${DO_CHECK}" = "check" ]; then
  echo ">> tsc check ..."
  ( cd "${OUT_DIR}" && npm install --silent --no-audit --no-fund && npx --yes tsc --noEmit )
  echo ">> tsc passed."
fi
