/**
* GENERATED BY KRPC GEN - LESS MODIFY BY HAND
* bookshelf-server-dto.ts
*/

export const APP = 'bookshelf-server';

export interface  BookCountResult {


    //// Total number of books / 图书总数
    total: number;
}

export interface  BookDetail {


    //// Book id (String carries a big integer) / 图书 ID（String 承载大整数）
    bookId: string;


    //// Title / 书名
    title: string;


    //// Author / 作者
    author: string;


    //// ISBN-13 / 国际标准书号
    isbn: string;


    //// Price in integer cents (minor units; never a float) / 价格，单位：分（整数分，禁止浮点）
    priceCents: number;


    //// Publication year / 出版年份
    publishedYear: number;
}

export interface  BookListResult {


    //// Books (ordered by title) / 图书列表（按书名排序）
    list: Array<BookDetail>;
}

export class  GetBookReq {


    // Book id (String carries a big integer) / 图书 ID（String 承载大整数）
    bookId: string;

	constructor(bookId: string) {
		this.bookId = bookId;
	}
}

export class  ListBooksReq {


    // Optional author substring filter (case-insensitive; null/blank = all books) / 可选作者子串过滤（不区分大小写；null/空 = 全部）
    authorContains?: string;
}

