/**
* GENERATED BY KRPC GEN - LESS MODIFY BY HAND
* bookshelf-service.ts
*/
import type { R, RpcService, MethodConfig as M } from 'krpc-base';

import type { BookListResult, GetBookReq, BookDetail, ListBooksReq, BookCountResult } from './bookshelf-server-dto';

const _ = 'Bookshelf/';

export class BookshelfService {

  constructor(readonly r: RpcService) {}
  
  countBooks(m?: M): R<BookCountResult>{
    return this.r.async(_ + 'countBooks', undefined, m);
  }
  
  getBook(d:GetBookReq, m?: M): R<BookDetail>{
    return this.r.async(_ + 'getBook', d, m);
  }
  
  listBooks(d:ListBooksReq, m?: M): R<BookListResult>{
    return this.r.async(_ + 'listBooks', d, m);
  }
}
